/*
 * Seerema Business Solutions - http://www.seerema.com/
 * 
 * Copyright 2020 IvaLab Inc. and by respective contributors (see below).
 * 
 * Released under the LGPL v3 or higher
 * See http://www.gnu.org/licenses/lgpl.txt
 *
 * Contributors:
 * 
 */

package com.seerema.shared.jpa.base.shared;

public enum ErrorCodes {

// @formatter:off
  
  ID_FIELD_NOT_FOUND, INVALID_DTO, ERROR_SET_ENTITY_ID,
  ERROR_READ_USERS, ERROR_FIND_USER, ERROR_CREATE_USER, ERROR_FIND_USER_NAME,
  INVALID_UPDATE_ENTITY, USER_ACCESS_DENIED,
  
  ERROR_CREATE_BINARY_FILE, ERROR_READ_BINARY_FILE, ERROR_READ_BINARY_FILES, ERROR_UPDATE_BINARY_FILE, ERROR_DELETE_BINARY_FILE,
  ERROR_CREATE_BFILE_CAT, ERROR_READ_BFILE_CAT, ERROR_READ_BFILE_CATS, ERROR_UPDATE_BFILE_CAT, ERROR_DELETE_BFILE_CAT,
  ERROR_CREATE_FIELD_CAT, ERROR_READ_FIELD_CAT, ERROR_READ_FIELD_CATS, ERROR_UPDATE_FIELD_CAT, ERROR_DELETE_FIELD_CAT,
  ERROR_CREATE_FIELD, ERROR_READ_FIELD, ERROR_READ_FIELDS, ERROR_UPDATE_FIELD, ERROR_DELETE_FIELD,
  ERROR_CREATE_ENTITY, ERROR_READ_ENTITY, ERROR_READ_ENTITIES, ERROR_UPDATE_ENTITY, ERROR_DELETE_ENTITY

// @formatter:on

}
